# Generated by Django 3.0 on 2022-07-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='eststate_list',
            field=models.TextField(blank=True, default=''),
        ),
    ]
