# Generated by Django 3.0 on 2022-07-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='websocket_url',
            field=models.TextField(default=''),
        ),
    ]
