# Generated by Django 3.0 on 2022-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_remove_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokersusers',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
