# Generated by Django 3.0 on 2022-05-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_brokersusers_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokersusers',
            name='balance',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
