# Generated by Django 3.0 on 2022-04-04 13:35

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=128)),
                ('area', models.CharField(default='', max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. 10 digit mobile number.", regex='^\\d{10}$')])),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=128, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('mobile', models.CharField(blank=True, max_length=64)),
                ('mail', models.CharField(blank=True, max_length=64)),
                ('client_details', models.TextField(blank=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='surat', max_length=128)),
                ('employee', models.CharField(default='surat', max_length=128)),
                ('estate', models.CharField(default='surat', max_length=128)),
                ('contact_time', models.TextField()),
                ('contact_details', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_name', models.CharField(max_length=255)),
                ('city', models.CharField(default='', max_length=128)),
                ('estate_type', models.CharField(default='', max_length=128)),
                ('floor_space', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('number_of_balconies', models.IntegerField(blank=True)),
                ('balconies_space', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('number_of_bedrooms', models.IntegerField(blank=True)),
                ('number_of_bathrooms', models.IntegerField(blank=True)),
                ('number_of_garages', models.IntegerField(blank=True)),
                ('number_of_parking_spaces', models.IntegerField(blank=True)),
                ('pets_allowed', models.IntegerField(blank=True)),
                ('estate_description', models.TextField()),
                ('estate_status', models.CharField(default='', max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
                ('society', models.CharField(default='', max_length=128)),
                ('area', models.CharField(default='', max_length=128)),
                ('broker_mobile', models.CharField(default='', max_length=128)),
                ('broker_name', models.CharField(default='', max_length=128)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_status_name', models.CharField(max_length=64, unique=True)),
                ('is_deleted', models.BooleanField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128)),
                ('is_deleted', models.BooleanField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.CharField(default='', max_length=128)),
                ('broker', models.CharField(default='', max_length=128)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_id', models.CharField(default='', max_length=128)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubestateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_name', models.CharField(max_length=128)),
                ('estate_type', models.CharField(default='surat', max_length=128)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=128)),
                ('city', models.CharField(default='surat', max_length=128)),
                ('pincode', models.IntegerField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
                'unique_together': {('area_name', 'city')},
            },
        ),
    ]
