# Generated by Django 3.0 on 2022-04-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_broker_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='budget',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
