# Generated by Django 3.0 on 2022-05-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_estate_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='balance',
        ),
    ]
