# Generated by Django 3.0 on 2022-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_broker_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryQuerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_number', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=128)),
                ('estate_type', models.CharField(max_length=128)),
                ('budget', models.CharField(max_length=128)),
                ('area', models.CharField(max_length=128)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
