# Generated by Django 3.0 on 2022-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_enquiryquerys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryquerys',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
