# Generated by Django 3.0 on 2022-06-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20220505_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='furniture',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='enquiryquerys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='number_of_bedrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
