# Generated by Django 3.0 on 2022-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20220611_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='budget',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
