# Generated by Django 3.0 on 2022-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220611_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='furniture',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
