# Generated by Django 3.0 on 2022-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220611_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='estate_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
